### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by Ivanverdonck** [davidborzek/tvhgo#539]
I tried to run it using docker, but get following errors:
is the volume path correct? or is there an other error?

`docker run -d \
    --name tvhgo \
    -p 9983:8080 \
    -e 'TVHGO_TVHEADEND_HOST=10.0.1.30' \
    -v /volume1/docker/tvhgo:/tvhgo \
    --restart unless-stopped \
    ghcr.io/davidborzek/tvhgo:latest`

2024/04/20 15:03:30,stdout,[90m2024-04-20T13:03:30Z[0m [31mFTL[0m [1m../build/cmd/server/server.go:51[0m[36m >[0m [1mfailed to connect to database[0m [36merror=[0m[31m[1m"unable to open database file: no such file or directory"[0m[0m

2024/04/20 15:03:30,stdout,[90m2024-04-20T13:03:30Z[0m [32mINF[0m [1m../build/cmd/server/server.go:47[0m[36m >[0m [1mtvhgo started[0m [36mpid=[0m1

Kind regards,
Ivan.

**Comment by davidborzek** [comment]
Hey, the command looks correct, did you check the permissions of the `/volume1/docker/tvhgo` directory?

tvhgo runs as `1000:1000` (normally this should be your default non-root user). Try to set these using:

```
chown -R 1000:1000 /volume1/docker/tvhgo
```

I will add these information to the docs.
