### ISSUE TITLE
Change time format

### ISSUE THREAD

**Issue by helio58** [davidborzek/tvhgo#540]
Hi , is possible to change the time format?
Im getting am and pm will like to have 24H
Thanks

**Comment by davidborzek** [comment]
Hey, the time format depends on the configured language of the web interface (currently only English and German are supported).  If needed, I can implement a separate option to change the time format.

**Comment by helio58** [comment]
> Hey, the time format depends on the configured language of the web interface (currently only English and German are supported). If needed, I can implement a separate option to change the time format.

Thanks David, I haven tried the German option. Nu I see the 24H stile. But I think it's a good option to be able to toggle to 24H with English language. Thanks for this app. Jose

**Comment by davidborzek** [comment]
I have implemented the time format option in the web interface settings. It will be included in the next release.

If you want to test it right now, you can use the docker image build from the main branch: `ghcr.io/davidborzek/tvhgo:main`.

**Comment by helio58** [comment]
> I have implemented the time format option in the web interface settings. It will be included in the next release.
> 
> If you want to test it right now, you can use the docker image build from the main branch: `ghcr.io/davidborzek/tvhgo:main`.

Thanks works great
